version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: >
      --deterministic
      --gasLimit 20000000
      --allowUnlimitedContractSize
      --networkId 1337
      --chainId 1337
    ports:
      - 8545:8545
  contracts:
    image: lok52/zp-contracts:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.contracts
      args:
        - VERIFIER_IMAGE=lok52/verifier:latest
    depends_on:
      - verifier
      - ganache
  verifier:
    image: lok52/verifier:latest
    build:
      context: ./docker
      dockerfile: Dockerfile.verifier
  redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
    ports:
      - 6379:6379
  relayer:
    image: lok52/zp-relayer:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.relayer
      args:
        - VERIFIER_IMAGE=lok52/verifier:latest
    volumes:
      - relayer_tree:/app/tree.db
      - relayer_txs:/app/txs.db
    env_file: zp-relayer/.env
    ports:
      - 8000:8000
    depends_on:
      - verifier

volumes:
  relayer_tree:
  relayer_txs:
