#!/usr/bin/env bash

USERNAME=voidxnull
IMAGE=zeropool-relayer

docker build -f ./docker/Dockerfile.relayer -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:$VERSION
